process_transcript_task:
  description: "This task involves analyzing a conversation transcript between a potential customer 
  interested in travel insurance and a customer service representative from ShiokAh Insurance. 
  The goal is to extract key customer details from the transcript, such as age, medical conditions, 
  destination, coverage preferences, and customization requests. This extracted information will be 
  organized into a Python list and used by an underwriter to determine policy suitability."
  expected_output: A Python list

generate_underwriting_report_task:
  description: "This task requires you to generate a comprehensive underwriting report in Markdown format. 
  The report will be based on your review of a travel insurance policy.
  This report is for the Chief Underwriter and should focus on accurately extracting relevant information from both sources. 
  Please use clear and concise Markdown formatting to structure the report. 
  Remember, this is not a policy recommendation. The goal is to provide a structured analysis of customer information 
  in relation to the policy details."
  expected_output: "The report should be in Markdown format and follow this structure: First, include a 
  'Policy Summary' section using a top-level heading (# Policy Summary). Then, create separate sections for 
  each piece of customer information (age, medical conditions, destination, coverage factors, policy 
  customization factors) using second-level headings (## Age, ## Medical Conditions, etc.). In each section, 
  extract relevant information, cross-reference it with the policy details to highlight potential premiums, 
  exclusions, or other underwriting considerations, and provide examples from the transcript to support your 
  analysis. Use Markdown elements like bullet points and bold text for clarity."