process_transcript_task:
  description: "This task involves analyzing a conversation transcript between a potential customer 
  interested in travel insurance and a customer service representative from ShiokAh Insurance. 
  The goal is to extract key customer details from the transcript, such as age, medical conditions, 
  destination, coverage preferences, customization requests and coverage priorities. This extracted information will be 
  organized into a Python list and used by an underwriter to determine policy suitability."
  expected_output: A Python list

generate_underwriting_report_task:
  description: >
    This task requires you to generate a comprehensive underwriting report in Markdown format to assess how suitable a travel 
    insurance policy is for a customer's given coverage priorities.
    This report is for the Recommendation Agent and should focus on accurately extracting relevant information 
    from the provided customer data and cross-referencing it with the policy details. Use clear and concise Markdown 
    formatting to structure the report.
  expected_output: >
    The report should be in Markdown format and follow this structure: First section focuses on the coverage priorities that the 
    customer has provided, and identifies maximum eligible policy benefits based on the other information provided (age, medical 
    conditions, destination, coverage_factors, policy_customization_factors) and what is stated in the policy.
    Do highlight potential benefits, premiums, exclusions, or other underwriting considerations, and provide clear references to the 
    policy where applicable (plan/tier/conditions, etc to support your analysis. Use Markdown elements such as bullet points and 
    bold text for clarity. 
    In the second and final section, give your expert opinion how well the coverage priorities are met. 
    This is not a recommendation but an objective analysis, based on your expert underwriting judgement.
    The title of the report should concatenate the insurer and type of benefit in the format '{name_of_insurer}_{type_of_benefit}'.